import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

export const ROOT = fileURLToPath(new URL('../../', import.meta.url));
export const DATA = join(ROOT, 'data');
export const HOPS_DIR = join(DATA, 'hops');
export const SCHEMA_DIR = join(ROOT, 'schema');
export const DIST = join(ROOT, 'dist');

const readYaml = (path) => YAML.parse(readFileSync(path, 'utf8')) ?? {};

export const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));

/**
 * Loads everything in data/ into one object. Deliberately does no validation and
 * no rolling up — validate.js and build.js each do their own thing with this.
 */
export function loadDataset() {
  const sources = readYaml(join(DATA, 'sources.yml'));

  const taxonomy = {
    aromaTags: readYaml(join(DATA, 'taxonomy', 'aroma-tags.yml')),
    beerStyles: readYaml(join(DATA, 'taxonomy', 'beer-styles.yml')),
    countries: readYaml(join(DATA, 'taxonomy', 'countries.yml')),
    breeders: readYaml(join(DATA, 'taxonomy', 'breeders.yml')),
  };

  const hops = readdirSync(HOPS_DIR)
    .filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))
    .map((file) => ({
      file,
      expectedSlug: basename(file).replace(/\.ya?ml$/, ''),
      ...readYaml(join(HOPS_DIR, file)),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  // Generated by tools/ingest/usda_nass.py; optional so a fresh fork without
  // it still builds.
  const acreagePath = join(DATA, 'acreage', 'usda-nass.yml');
  const acreage = existsSync(acreagePath) ? readYaml(acreagePath) : null;

  // Beers: generated by tools/ingest/beers.py, one file per brewery.
  const beersDir = join(DATA, 'beers');
  // data/beers/scanned/ holds beers added from the /scan/ page. A brewery can
  // appear in both (crawled from its website and scanned from a can), so
  // files for the same brewery slug merge; the crawled entry wins a tie.
  const beerFiles = existsSync(beersDir)
    ? [
        ...readdirSync(beersDir).filter((f) => f.endsWith('.yml') && f !== 'overrides.yml').sort(),
        ...(existsSync(join(beersDir, 'scanned'))
          ? readdirSync(join(beersDir, 'scanned')).filter((f) => f.endsWith('.yml')).sort().map((f) => `scanned/${f}`)
          : []),
      ]
    : [];
  const bySlug = new Map();
  for (const f of beerFiles) {
    const doc = { file: f, ...readYaml(join(beersDir, f)) };
    const have = bySlug.get(doc.brewery?.slug);
    if (!have) {
      bySlug.set(doc.brewery?.slug, doc);
      continue;
    }
    const seen = new Set(have.beers.map((b) => b.slug));
    have.beers = [...have.beers, ...(doc.beers ?? []).filter((b) => !seen.has(b.slug))];
  }
  // A crawled beer none of whose "hops" matched a record is usually a page
  // that listed malts, "aged hops" or a joke where the hops go; it stays in
  // the data but not on the site. A scanned beer always shows: a person
  // chose to add it.
  for (const doc of bySlug.values()) {
    doc.beers = doc.beers.filter((beer) => beer.scanned || (beer.hops ?? []).some((h) => h.hop));
  }
  const breweries = [...bySlug.values()].filter((doc) => doc.beers.length);

  // Hand corrections from the Edit form (tools/ingest/edit_beer.py), laid
  // over whatever the crawler or a scan wrote.
  const overridesPath = join(beersDir, 'overrides.yml');
  const overrides = existsSync(overridesPath) ? readYaml(overridesPath) : {};
  for (const doc of breweries) {
    const b = overrides.breweries?.[doc.brewery?.slug];
    if (b) doc.brewery = { ...doc.brewery, ...b };
    for (const beer of doc.beers) {
      const e = overrides.beers?.[`${doc.brewery.slug}/${beer.slug}`];
      if (e) Object.assign(beer, e);
    }
  }

  // Brooks's own drinking: Untappd check-ins (tools/ingest/untappd.py) and
  // ratings set on HopLove (tools/ingest/rating.py). Both optional.
  const checkinsPath = join(DATA, 'untappd', 'checkins.yml');
  const checkins = existsSync(checkinsPath) ? readYaml(checkinsPath).checkins ?? [] : [];
  const historyPath = join(DATA, 'untappd', 'history.yml');
  const history = existsSync(historyPath) ? readYaml(historyPath).beers ?? [] : [];
  const ratingsPath = join(DATA, 'ratings.yml');
  const ratings = existsSync(ratingsPath) ? readYaml(ratingsPath).ratings ?? [] : [];

  return { sources, taxonomy, hops, acreage, breweries, checkins, ratings, overrides, history };
}

export const schemas = () => ({
  hop: readJson(join(SCHEMA_DIR, 'hop.schema.json')),
  source: readJson(join(SCHEMA_DIR, 'source.schema.json')),
  taxonomy: readJson(join(SCHEMA_DIR, 'taxonomy.schema.json')),
});

/** Every metric key the schema knows about, so tooling never hardcodes a list. */
export const METRIC_KEYS = ['alpha_acid', 'beta_acid', 'cohumulone', 'total_oil', 'hsi', 'alpha_retention_6mo_20c'];
export const OIL_KEYS = ['myrcene', 'humulene', 'caryophyllene', 'farnesene', 'linalool', 'geraniol', 'pinene', 'selinene', 'other'];

/** Every analytics/oils metric on a hop that actually has observations. */
export function allMetrics(hop) {
  return [
    ...METRIC_KEYS.map((k) => hop.analytics?.[k]),
    ...OIL_KEYS.map((k) => hop.oils?.[k]),
  ].filter((m) => m?.observations);
}

/**
 * Every source id a hop record cites, across every field that can carry a
 * `refs`/`source` key. Single source of truth for "what does this record
 * cite" — validate.js and coverage.js both need this, and having it defined
 * twice is exactly how the ychr/mill95 false-warning bug happened.
 */
export function allRefs(hop) {
  return [
    ...(hop.aroma?.refs ?? []),
    ...(hop.pedigree?.refs ?? []),
    ...(hop.products?.refs ?? []),
    ...(hop.substitutes ?? []).flatMap((s) => s.refs ?? []),
    ...(hop.forms ?? []).flatMap((f) => f.refs ?? []),
    ...allMetrics(hop).flatMap((m) => m.observations.map((o) => o.source)),
  ];
}

export const c = {
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
};
